import random
import os
import sys
import glob
import shutil
import subprocess

import cocotb
from cocotb.clock import Clock
from cocotb.runner import get_runner
from cocotb.triggers import FallingEdge
from cocotb.triggers import RisingEdge, Timer
from cocotb.binary import BinaryValue
from pathlib import Path

@cocotb.test()
async def my_first_test(dut):
    """Test a design without clock signals."""
    random.seed(42)

    clock = Clock(dut.CK, 2, units="ns")  # Create a 10ns period clock on port clk
    cocotb.start_soon(clock.start())  # Start the clock
    await RisingEdge(dut.CK)

    # Simulate 10 cycles (or steps) without clock
    for cycle in range(10000):
        await RisingEdge(dut.CK)
        dut.N1.value = random.randint(0, 1)
        dut.N5.value = random.randint(0, 1)
        dut.N9.value = random.randint(0, 1)
        dut.N12.value = random.randint(0, 1)
        dut.N15.value = random.randint(0, 1)
        dut.N18.value = random.randint(0, 1)
        dut.N23.value = random.randint(0, 1)
        dut.N26.value = random.randint(0, 1)
        dut.N29.value = random.randint(0, 1)
        dut.N32.value = random.randint(0, 1)
        dut.N35.value = random.randint(0, 1)
        dut.N38.value = random.randint(0, 1)
        dut.N41.value = random.randint(0, 1)
        dut.N44.value = random.randint(0, 1)
        dut.N47.value = random.randint(0, 1)
        dut.N50.value = random.randint(0, 1)
        dut.N53.value = random.randint(0, 1)
        dut.N54.value = random.randint(0, 1)
        dut.N55.value = random.randint(0, 1)
        dut.N56.value = random.randint(0, 1)
        dut.N57.value = random.randint(0, 1)
        dut.N58.value = random.randint(0, 1)
        dut.N59.value = random.randint(0, 1)
        dut.N60.value = random.randint(0, 1)
        dut.N61.value = random.randint(0, 1)
        dut.N62.value = random.randint(0, 1)
        dut.N63.value = random.randint(0, 1)
        dut.N64.value = random.randint(0, 1)
        dut.N65.value = random.randint(0, 1)
        dut.N66.value = random.randint(0, 1)
        dut.N69.value = random.randint(0, 1)
        dut.N70.value = random.randint(0, 1)
        dut.N73.value = random.randint(0, 1)
        dut.N74.value = random.randint(0, 1)
        dut.N75.value = random.randint(0, 1)
        dut.N76.value = random.randint(0, 1)
        dut.N77.value = random.randint(0, 1)
        dut.N78.value = random.randint(0, 1)
        dut.N79.value = random.randint(0, 1)
        dut.N80.value = random.randint(0, 1)
        dut.N81.value = random.randint(0, 1)
        dut.N82.value = random.randint(0, 1)
        dut.N83.value = random.randint(0, 1)
        dut.N84.value = random.randint(0, 1)
        dut.N85.value = random.randint(0, 1)
        dut.N86.value = random.randint(0, 1)
        dut.N87.value = random.randint(0, 1)
        dut.N88.value = random.randint(0, 1)
        dut.N89.value = random.randint(0, 1)
        dut.N94.value = random.randint(0, 1)
        dut.N97.value = random.randint(0, 1)
        dut.N100.value = random.randint(0, 1)
        dut.N103.value = random.randint(0, 1)
        dut.N106.value = random.randint(0, 1)
        dut.N109.value = random.randint(0, 1)
        dut.N110.value = random.randint(0, 1)
        dut.N111.value = random.randint(0, 1)
        dut.N112.value = random.randint(0, 1)
        dut.N113.value = random.randint(0, 1)
        dut.N114.value = random.randint(0, 1)
        dut.N115.value = random.randint(0, 1)
        dut.N118.value = random.randint(0, 1)
        dut.N121.value = random.randint(0, 1)
        dut.N124.value = random.randint(0, 1)
        dut.N127.value = random.randint(0, 1)
        dut.N130.value = random.randint(0, 1)
        dut.N133.value = random.randint(0, 1)
        dut.N134.value = random.randint(0, 1)
        dut.N135.value = random.randint(0, 1)
        dut.N138.value = random.randint(0, 1)
        dut.N141.value = random.randint(0, 1)
        dut.N144.value = random.randint(0, 1)
        dut.N147.value = random.randint(0, 1)
        dut.N150.value = random.randint(0, 1)
        dut.N151.value = random.randint(0, 1)
        dut.N152.value = random.randint(0, 1)
        dut.N153.value = random.randint(0, 1)
        dut.N154.value = random.randint(0, 1)
        dut.N155.value = random.randint(0, 1)
        dut.N156.value = random.randint(0, 1)
        dut.N157.value = random.randint(0, 1)
        dut.N158.value = random.randint(0, 1)
        dut.N159.value = random.randint(0, 1)
        dut.N160.value = random.randint(0, 1)
        dut.N161.value = random.randint(0, 1)
        dut.N162.value = random.randint(0, 1)
        dut.N163.value = random.randint(0, 1)
        dut.N164.value = random.randint(0, 1)
        dut.N165.value = random.randint(0, 1)
        dut.N166.value = random.randint(0, 1)
        dut.N167.value = random.randint(0, 1)
        dut.N168.value = random.randint(0, 1)
        dut.N169.value = random.randint(0, 1)
        dut.N170.value = random.randint(0, 1)
        dut.N171.value = random.randint(0, 1)
        dut.N172.value = random.randint(0, 1)
        dut.N173.value = random.randint(0, 1)
        dut.N174.value = random.randint(0, 1)
        dut.N175.value = random.randint(0, 1)
        dut.N176.value = random.randint(0, 1)
        dut.N177.value = random.randint(0, 1)
        dut.N178.value = random.randint(0, 1)
        dut.N179.value = random.randint(0, 1)
        dut.N180.value = random.randint(0, 1)
        dut.N181.value = random.randint(0, 1)
        dut.N182.value = random.randint(0, 1)
        dut.N183.value = random.randint(0, 1)
        dut.N184.value = random.randint(0, 1)
        dut.N185.value = random.randint(0, 1)
        dut.N186.value = random.randint(0, 1)
        dut.N187.value = random.randint(0, 1)
        dut.N188.value = random.randint(0, 1)
        dut.N189.value = random.randint(0, 1)
        dut.N190.value = random.randint(0, 1)
        dut.N191.value = random.randint(0, 1)
        dut.N192.value = random.randint(0, 1)
        dut.N193.value = random.randint(0, 1)
        dut.N194.value = random.randint(0, 1)
        dut.N195.value = random.randint(0, 1)
        dut.N196.value = random.randint(0, 1)
        dut.N197.value = random.randint(0, 1)
        dut.N198.value = random.randint(0, 1)
        dut.N199.value = random.randint(0, 1)
        dut.N200.value = random.randint(0, 1)
        dut.N201.value = random.randint(0, 1)
        dut.N202.value = random.randint(0, 1)
        dut.N203.value = random.randint(0, 1)
        dut.N204.value = random.randint(0, 1)
        dut.N205.value = random.randint(0, 1)
        dut.N206.value = random.randint(0, 1)
        dut.N207.value = random.randint(0, 1)
        dut.N208.value = random.randint(0, 1)
        dut.N209.value = random.randint(0, 1)
        dut.N210.value = random.randint(0, 1)
        dut.N211.value = random.randint(0, 1)
        dut.N212.value = random.randint(0, 1)
        dut.N213.value = random.randint(0, 1)
        dut.N214.value = random.randint(0, 1)
        dut.N215.value = random.randint(0, 1)
        dut.N216.value = random.randint(0, 1)
        dut.N217.value = random.randint(0, 1)
        dut.N218.value = random.randint(0, 1)
        dut.N219.value = random.randint(0, 1)
        dut.N220.value = random.randint(0, 1)
        dut.N221.value = random.randint(0, 1)
        dut.N222.value = random.randint(0, 1)
        dut.N223.value = random.randint(0, 1)
        dut.N224.value = random.randint(0, 1)
        dut.N225.value = random.randint(0, 1)
        dut.N226.value = random.randint(0, 1)
        dut.N227.value = random.randint(0, 1)
        dut.N228.value = random.randint(0, 1)
        dut.N229.value = random.randint(0, 1)
        dut.N230.value = random.randint(0, 1)
        dut.N231.value = random.randint(0, 1)
        dut.N232.value = random.randint(0, 1)
        dut.N233.value = random.randint(0, 1)
        dut.N234.value = random.randint(0, 1)
        dut.N235.value = random.randint(0, 1)
        dut.N236.value = random.randint(0, 1)
        dut.N237.value = random.randint(0, 1)
        dut.N238.value = random.randint(0, 1)
        dut.N239.value = random.randint(0, 1)
        dut.N240.value = random.randint(0, 1)
        dut.N242.value = random.randint(0, 1)
        dut.N245.value = random.randint(0, 1)
        dut.N248.value = random.randint(0, 1)
        dut.N251.value = random.randint(0, 1)
        dut.N254.value = random.randint(0, 1)
        dut.N257.value = random.randint(0, 1)
        dut.N260.value = random.randint(0, 1)
        dut.N263.value = random.randint(0, 1)
        dut.N267.value = random.randint(0, 1)
        dut.N271.value = random.randint(0, 1)
        dut.N274.value = random.randint(0, 1)
        dut.N277.value = random.randint(0, 1)
        dut.N280.value = random.randint(0, 1)
        dut.N283.value = random.randint(0, 1)
        dut.N286.value = random.randint(0, 1)
        dut.N289.value = random.randint(0, 1)
        dut.N293.value = random.randint(0, 1)
        dut.N296.value = random.randint(0, 1)
        dut.N299.value = random.randint(0, 1)
        dut.N303.value = random.randint(0, 1)
        dut.N307.value = random.randint(0, 1)
        dut.N310.value = random.randint(0, 1)
        dut.N313.value = random.randint(0, 1)
        dut.N316.value = random.randint(0, 1)
        dut.N319.value = random.randint(0, 1)
        dut.N322.value = random.randint(0, 1)
        dut.N325.value = random.randint(0, 1)
        dut.N328.value = random.randint(0, 1)
        dut.N331.value = random.randint(0, 1)
        dut.N334.value = random.randint(0, 1)
        dut.N337.value = random.randint(0, 1)
        dut.N340.value = random.randint(0, 1)
        dut.N343.value = random.randint(0, 1)
        dut.N346.value = random.randint(0, 1)
        dut.N349.value = random.randint(0, 1)
        dut.N352.value = random.randint(0, 1)
        dut.N355.value = random.randint(0, 1)
        dut.N358.value = random.randint(0, 1)
        dut.N361.value = random.randint(0, 1)
        dut.N364.value = random.randint(0, 1)
        dut.N367.value = random.randint(0, 1)
        dut.N382.value = random.randint(0, 1)
        dut.N241_I.value = random.randint(0, 1)



def runner():
    sim = os.getenv("SIM", "verilator")

    dir_path = os.path.dirname(os.path.abspath(__file__))
    sources = glob.glob(os.path.join(dir_path, "*.sv"))
    working_dir = os.getcwd()
    
    # set parameters
    extra_args = []
    extra_args.append(f"--trace")
    # extra_args.append("--lint-only")
    extra_args.append("-Wno-WIDTHEXPAND")
    extra_args.append("-Wno-WIDTHTRUNC")

    #debug of Args
    print("Args is ")
    print(extra_args)
    print("")

    runner = get_runner(sim)
    runner.build(
        verilog_sources=sources,
        hdl_toplevel="c7552",
        build_args=extra_args,
    )

    runner.test(hdl_toplevel="c7552", test_module="sim")


if __name__ == "__main__":
    runner()