import random
import os
import sys
import glob
import shutil
import subprocess

import cocotb
from cocotb.clock import Clock
from cocotb.runner import get_runner
from cocotb.triggers import FallingEdge
from cocotb.triggers import RisingEdge, Timer
from cocotb.binary import BinaryValue
from pathlib import Path

@cocotb.test()
async def my_first_test(dut):
    """Test a design without clock signals."""
    random.seed(42)
    

    clock = Clock(dut.CK, 2, units="ns")  # Create a 10ns period clock on port clk
    cocotb.start_soon(clock.start())  # Start the clock
    await RisingEdge(dut.CK)

    # Simulate 10 cycles (or steps) without clock
    for cycle in range(10000):
        # clk rising edge
        await RisingEdge(dut.CK)
        dut.N1.value = random.randint(0, 1)
        dut.N2.value = random.randint(0, 1)
        dut.N3.value = random.randint(0, 1)
        dut.N4.value = random.randint(0, 1)
        dut.N5.value = random.randint(0, 1)
        dut.N6.value = random.randint(0, 1)
        dut.N7.value = random.randint(0, 1)
        dut.N8.value = random.randint(0, 1)
        dut.N11.value = random.randint(0, 1)
        dut.N14.value = random.randint(0, 1)
        dut.N15.value = random.randint(0, 1)
        dut.N16.value = random.randint(0, 1)
        dut.N19.value = random.randint(0, 1)
        dut.N20.value = random.randint(0, 1)
        dut.N21.value = random.randint(0, 1)
        dut.N22.value = random.randint(0, 1)
        dut.N23.value = random.randint(0, 1)
        dut.N24.value = random.randint(0, 1)
        dut.N25.value = random.randint(0, 1)
        dut.N26.value = random.randint(0, 1)
        dut.N27.value = random.randint(0, 1)
        dut.N28.value = random.randint(0, 1)
        dut.N29.value = random.randint(0, 1)
        dut.N32.value = random.randint(0, 1)
        dut.N33.value = random.randint(0, 1)
        dut.N34.value = random.randint(0, 1)
        dut.N35.value = random.randint(0, 1)
        dut.N36.value = random.randint(0, 1)
        dut.N37.value = random.randint(0, 1)
        dut.N40.value = random.randint(0, 1)
        dut.N43.value = random.randint(0, 1)
        dut.N44.value = random.randint(0, 1)
        dut.N47.value = random.randint(0, 1)
        dut.N48.value = random.randint(0, 1)
        dut.N49.value = random.randint(0, 1)
        dut.N50.value = random.randint(0, 1)
        dut.N51.value = random.randint(0, 1)
        dut.N52.value = random.randint(0, 1)
        dut.N53.value = random.randint(0, 1)
        dut.N54.value = random.randint(0, 1)
        dut.N55.value = random.randint(0, 1)
        dut.N56.value = random.randint(0, 1)
        dut.N57.value = random.randint(0, 1)
        dut.N60.value = random.randint(0, 1)
        dut.N61.value = random.randint(0, 1)
        dut.N62.value = random.randint(0, 1)
        dut.N63.value = random.randint(0, 1)
        dut.N64.value = random.randint(0, 1)
        dut.N65.value = random.randint(0, 1)
        dut.N66.value = random.randint(0, 1)
        dut.N67.value = random.randint(0, 1)
        dut.N68.value = random.randint(0, 1)
        dut.N69.value = random.randint(0, 1)
        dut.N72.value = random.randint(0, 1)
        dut.N73.value = random.randint(0, 1)
        dut.N74.value = random.randint(0, 1)
        dut.N75.value = random.randint(0, 1)
        dut.N76.value = random.randint(0, 1)
        dut.N77.value = random.randint(0, 1)
        dut.N78.value = random.randint(0, 1)
        dut.N79.value = random.randint(0, 1)
        dut.N80.value = random.randint(0, 1)
        dut.N81.value = random.randint(0, 1)
        dut.N82.value = random.randint(0, 1)
        dut.N85.value = random.randint(0, 1)
        dut.N86.value = random.randint(0, 1)
        dut.N87.value = random.randint(0, 1)
        dut.N88.value = random.randint(0, 1)
        dut.N89.value = random.randint(0, 1)
        dut.N90.value = random.randint(0, 1)
        dut.N91.value = random.randint(0, 1)
        dut.N92.value = random.randint(0, 1)
        dut.N93.value = random.randint(0, 1)
        dut.N94.value = random.randint(0, 1)
        dut.N95.value = random.randint(0, 1)
        dut.N96.value = random.randint(0, 1)
        dut.N99.value = random.randint(0, 1)
        dut.N100.value = random.randint(0, 1)
        dut.N101.value = random.randint(0, 1)
        dut.N102.value = random.randint(0, 1)
        dut.N103.value = random.randint(0, 1)
        dut.N104.value = random.randint(0, 1)
        dut.N105.value = random.randint(0, 1)
        dut.N106.value = random.randint(0, 1)
        dut.N107.value = random.randint(0, 1)

        dut.N108.value = random.randint(0, 1)
        dut.N111.value = random.randint(0, 1)
        dut.N112.value = random.randint(0, 1)
        dut.N113.value = random.randint(0, 1)
        dut.N114.value = random.randint(0, 1)
        dut.N115.value = random.randint(0, 1)
        dut.N116.value = random.randint(0, 1)
        dut.N117.value = random.randint(0, 1)
        dut.N118.value = random.randint(0, 1)
        dut.N119.value = random.randint(0, 1)
        dut.N120.value = random.randint(0, 1)
        dut.N123.value = random.randint(0, 1)
        dut.N124.value = random.randint(0, 1)
        dut.N125.value = random.randint(0, 1)
        dut.N126.value = random.randint(0, 1)
        dut.N127.value = random.randint(0, 1)
        dut.N128.value = random.randint(0, 1)
        dut.N129.value = random.randint(0, 1)
        dut.N130.value = random.randint(0, 1)
        dut.N131.value = random.randint(0, 1)
        dut.N132.value = random.randint(0, 1)
        dut.N135.value = random.randint(0, 1)
        dut.N136.value = random.randint(0, 1)
        dut.N137.value = random.randint(0, 1)
        dut.N138.value = random.randint(0, 1)
        dut.N139.value = random.randint(0, 1)
        dut.N140.value = random.randint(0, 1)
        dut.N141.value = random.randint(0, 1)
        dut.N142.value = random.randint(0, 1)
        dut.N143_I.value = random.randint(0, 1)
        dut.N144_I.value = random.randint(0, 1)
        dut.N145_I.value = random.randint(0, 1)
        dut.N146_I.value = random.randint(0, 1)
        dut.N147_I.value = random.randint(0, 1)
        dut.N148_I.value = random.randint(0, 1)
        dut.N149_I.value = random.randint(0, 1)
        dut.N150_I.value = random.randint(0, 1)
        dut.N151_I.value = random.randint(0, 1)
        dut.N152_I.value = random.randint(0, 1)
        dut.N153_I.value = random.randint(0, 1)
        dut.N154_I.value = random.randint(0, 1)
        dut.N155_I.value = random.randint(0, 1)
        dut.N156_I.value = random.randint(0, 1)
        dut.N157_I.value = random.randint(0, 1)
        dut.N158_I.value = random.randint(0, 1)
        dut.N159_I.value = random.randint(0, 1)
        dut.N160_I.value = random.randint(0, 1)
        dut.N161_I.value = random.randint(0, 1)
        dut.N162_I.value = random.randint(0, 1)
        dut.N163_I.value = random.randint(0, 1)
        dut.N164_I.value = random.randint(0, 1)
        dut.N165_I.value = random.randint(0, 1)
        dut.N166_I.value = random.randint(0, 1)
        dut.N167_I.value = random.randint(0, 1)
        dut.N168_I.value = random.randint(0, 1)
        dut.N169_I.value = random.randint(0, 1)
        dut.N170_I.value = random.randint(0, 1)
        dut.N171_I.value = random.randint(0, 1)
        dut.N172_I.value = random.randint(0, 1)
        dut.N173_I.value = random.randint(0, 1)
        dut.N174_I.value = random.randint(0, 1)
        dut.N175_I.value = random.randint(0, 1)
        dut.N176_I.value = random.randint(0, 1)
        dut.N177_I.value = random.randint(0, 1)
        dut.N178_I.value = random.randint(0, 1)
        dut.N179_I.value = random.randint(0, 1)
        dut.N180_I.value = random.randint(0, 1)
        dut.N181_I.value = random.randint(0, 1)
        dut.N182_I.value = random.randint(0, 1)
        dut.N183_I.value = random.randint(0, 1)
        dut.N184_I.value = random.randint(0, 1)
        dut.N185_I.value = random.randint(0, 1)
        dut.N186_I.value = random.randint(0, 1)
        dut.N187_I.value = random.randint(0, 1)
        dut.N188_I.value = random.randint(0, 1)
        dut.N189_I.value = random.randint(0, 1)
        dut.N190_I.value = random.randint(0, 1)
        dut.N191_I.value = random.randint(0, 1)
        dut.N192_I.value = random.randint(0, 1)
        dut.N193_I.value = random.randint(0, 1)
        dut.N194_I.value = random.randint(0, 1)
        dut.N195_I.value = random.randint(0, 1)
        dut.N196_I.value = random.randint(0, 1)
        dut.N197_I.value = random.randint(0, 1)
        dut.N198_I.value = random.randint(0, 1)
        dut.N199_I.value = random.randint(0, 1)
        dut.N200_I.value = random.randint(0, 1)
        dut.N201_I.value = random.randint(0, 1)
        dut.N202_I.value = random.randint(0, 1)
        dut.N203_I.value = random.randint(0, 1)
        dut.N204_I.value = random.randint(0, 1)
        dut.N205_I.value = random.randint(0, 1)
        dut.N206_I.value = random.randint(0, 1)
        dut.N207_I.value = random.randint(0, 1)
        dut.N208_I.value = random.randint(0, 1)
        dut.N209_I.value = random.randint(0, 1)
        dut.N210_I.value = random.randint(0, 1)
        dut.N211_I.value = random.randint(0, 1)
        dut.N212_I.value = random.randint(0, 1)
        dut.N213_I.value = random.randint(0, 1)
        dut.N214_I.value = random.randint(0, 1)
        dut.N215_I.value = random.randint(0, 1)
        dut.N216_I.value = random.randint(0, 1)
        dut.N217_I.value = random.randint(0, 1)
        dut.N218_I.value = random.randint(0, 1)
        dut.N219.value = random.randint(0, 1)
        dut.N224.value = random.randint(0, 1)
        dut.N227.value = random.randint(0, 1)
        dut.N230.value = random.randint(0, 1)
        dut.N231.value = random.randint(0, 1)
        dut.N234.value = random.randint(0, 1)
        dut.N237.value = random.randint(0, 1)
        dut.N241.value = random.randint(0, 1)
        dut.N246.value = random.randint(0, 1)
        dut.N253.value = random.randint(0, 1)
        dut.N256.value = random.randint(0, 1)
        dut.N259.value = random.randint(0, 1)
        dut.N262.value = random.randint(0, 1)
        dut.N263.value = random.randint(0, 1)
        dut.N266.value = random.randint(0, 1)
        dut.N269.value = random.randint(0, 1)
        dut.N272.value = random.randint(0, 1)
        dut.N275.value = random.randint(0, 1)
        dut.N278.value = random.randint(0, 1)
        dut.N281.value = random.randint(0, 1)
        dut.N284.value = random.randint(0, 1)
        dut.N287.value = random.randint(0, 1)
        dut.N290.value = random.randint(0, 1)
        dut.N294.value = random.randint(0, 1)
        dut.N297.value = random.randint(0, 1)
        dut.N301.value = random.randint(0, 1)
        dut.N305.value = random.randint(0, 1)
        dut.N309.value = random.randint(0, 1)
        dut.N313.value = random.randint(0, 1)
        dut.N316.value = random.randint(0, 1)
        dut.N319.value = random.randint(0, 1)
        dut.N322.value = random.randint(0, 1)
        dut.N325.value = random.randint(0, 1)
        dut.N328.value = random.randint(0, 1)
        dut.N331.value = random.randint(0, 1)
        dut.N334.value = random.randint(0, 1)
        dut.N337.value = random.randint(0, 1)
        dut.N340.value = random.randint(0, 1)
        dut.N343.value = random.randint(0, 1)
        dut.N346.value = random.randint(0, 1)
        dut.N349.value = random.randint(0, 1)
        dut.N352.value = random.randint(0, 1)
        dut.N355.value = random.randint(0, 1)



def runner():
    sim = os.getenv("SIM", "verilator")

    dir_path = os.path.dirname(os.path.abspath(__file__))
    sources = glob.glob(os.path.join(dir_path, "*.sv"))
    working_dir = os.getcwd()
    
    # set parameters
    extra_args = []
    extra_args.append(f"--trace")
    # extra_args.append("--lint-only")
    extra_args.append("-Wno-WIDTHEXPAND")
    extra_args.append("-Wno-WIDTHTRUNC")

    #debug of Args
    print("Args is ")
    print(extra_args)
    print("")

    runner = get_runner(sim)
    runner.build(
        verilog_sources=sources,
        hdl_toplevel="c2670",
        build_args=extra_args,
    )

    runner.test(hdl_toplevel="c2670", test_module="sim")


if __name__ == "__main__":
    runner()