// The Verilator side of simgen: generate a C++ testbench, build it, run it.
//
// Verilator is the default simulator because it is cycle-based and 2-state.
// Both properties matter here beyond speed: no x/z leaks into the traces to
// disqualify constraints, and a design driven into a zero-delay feedback loop
// settles instead of spinning forever at one timestamp.
//
// The stimulus is the same as the Icarus path's — the semantics are the spec
// (gen_bench.render_sim_py), not the language it is written in.

#include "Harness.h"

#include <cctype>
#include <filesystem>
#include <sstream>

namespace smart {
namespace simgen {
namespace {

namespace fs = std::filesystem;

int effectiveWidth(int width) { return width > 0 ? width : 1; }

// C++ type Verilator gives a signal of this width.
const char* cppType(int width) {
    const int w = effectiveWidth(width);
    if (w <= 8) return "CData";
    if (w <= 16) return "SData";
    if (w <= 32) return "IData";
    return "QData";
}

// A draw of `width` random bits, as a C++ expression.
std::string randomDraw(int width) {
    const int w = effectiveWidth(width);
    if (w >= 64) return "((static_cast<QData>(::random()) << 32) ^ ::random())";
    if (w >= 32) return "static_cast<IData>(::random())";
    // ::random() yields 31 usable bits; masking below that is exact.
    return "(::random() & ((1u << " + std::to_string(w) + ") - 1u))";
}

// Internal free registers are reached through Verilator's flattened public
// names: --public-flat-rw exposes them on the root as <top>__DOT__<name>.
std::string freeRegRef(const std::string& top, const std::string& name) {
    return "top->rootp->" + top + "__DOT__" + name;
}

std::string driveLine(const std::string& target, int width,
                      const SignalSpec* spec, const std::string& indent) {
    if (spec != nullptr && !spec->values.empty()) {
        std::ostringstream os;
        os << indent << "{\n"
           << indent << "  static const long long choices[] = {";
        for (std::size_t i = 0; i < spec->values.size(); ++i)
            os << (i ? ", " : "") << spec->values[i];
        os << "};\n"
           << indent << "  " << target << " = choices[::random() % "
           << spec->values.size() << "];\n"
           << indent << "}\n";
        return os.str();
    }
    if (spec != nullptr && spec->constant.has_value())
        return indent + target + " = " + std::to_string(*spec->constant) + ";\n";
    if (spec != nullptr && spec->maxValue.has_value())
        return indent + target + " = ::random() % " +
               std::to_string(*spec->maxValue + 1) + ";\n";
    return indent + target + " = " + randomDraw(width) + ";\n";
}

const SignalSpec* specFor(const HarnessOptions& options, const std::string& name) {
    auto it = options.inputs.find(name);
    return it == options.inputs.end() ? nullptr : &it->second;
}

}  // namespace

std::string renderVerilatorHarness(const frontend::ModuleInfo& info,
                                   const HarnessOptions& options) {
    const auto clock = options.clock.empty()
                           ? frontend::guessClock(info)
                           : std::optional<std::string>(options.clock);
    const auto reset = clock ? (options.reset ? options.reset
                                              : frontend::guessReset(info, clock))
                             : std::optional<frontend::ResetInfo>();

    const std::string model = "V" + info.top;
    const bool hasFreeRegs = !info.freeRegs.empty();

    std::ostringstream os;
    os << "// Auto-generated by SMART (simgen/Verilator.cpp) — do not edit.\n"
       << "// Design: " << info.top
       << "  clock: " << (clock ? *clock : "none (combinational)")
       << "  reset: " << (reset ? reset->signal : "none") << "\n"
       << "#include <verilated.h>\n"
       << "#include <verilated_vcd_c.h>\n"
       << "#include \"" << model << ".h\"\n";
    if (hasFreeRegs) os << "#include \"" << model << "___024root.h\"\n";
    os << "#include <cstdlib>\n"
       << "#include <string>\n\n"
       << "int main(int argc, char** argv) {\n"
       << "    unsigned seed = " << options.seed << ";\n"
       << "    std::string vcdPath = \"dump.vcd\";\n"
       << "    for (int i = 1; i < argc; ++i) {\n"
       << "        const std::string arg = argv[i];\n"
       << "        if (arg.rfind(\"+seed=\", 0) == 0) seed = std::stoul(arg.substr(6));\n"
       << "        else if (arg.rfind(\"+vcd=\", 0) == 0) vcdPath = arg.substr(5);\n"
       << "    }\n\n"
       << "    Verilated::traceEverOn(true);\n"
       << "    " << model << "* top = new " << model << ";\n"
       << "    VerilatedVcdC* trace = new VerilatedVcdC;\n"
       << "    top->trace(trace, 99);\n"
       << "    trace->open(vcdPath.c_str());\n"
       << "    ::srandom(seed);\n\n"
       << "    vluint64_t now = 0;\n";

    // anyconst: drawn once, before anything runs.
    for (const auto& reg : info.freeRegs) {
        if (reg.kind != "anyconst") continue;
        os << driveLine(freeRegRef(info.top, reg.name), reg.width,
                        specFor(options, reg.name), "    ");
    }

    std::vector<frontend::Port> driven;
    for (const auto& port : info.inputs()) {
        if (clock && port.name == *clock) continue;
        if (reset && port.name == reset->signal) continue;
        driven.push_back(port);
    }

    if (clock) {
        os << "\n    top->" << *clock << " = 0;\n";
        if (reset) {
            os << "    top->" << reset->signal << " = " << reset->active << ";\n"
               << "    for (int i = 0; i < " << reset->cycles << "; ++i) {\n"
               << "        top->" << *clock << " = 1; top->eval(); trace->dump(now); now += 5;\n"
               << "        top->" << *clock << " = 0; top->eval(); trace->dump(now); now += 5;\n"
               << "    }\n"
               << "    top->" << reset->signal << " = " << (1 - reset->active) << ";\n";
        }
    }

    os << "\n    for (int cycle = 0; cycle < " << options.cycles << "; ++cycle) {\n";
    for (const auto& port : driven)
        os << driveLine("top->" + port.name, port.width, specFor(options, port.name),
                        "        ");
    for (const auto& reg : info.freeRegs) {
        if (reg.kind != "anyseq") continue;
        os << driveLine(freeRegRef(info.top, reg.name), reg.width,
                        specFor(options, reg.name), "        ");
    }

    if (clock) {
        // One full clock period per cycle, sampled on both edges so the trace
        // carries the settled values either side of the edge.
        os << "        top->" << *clock << " = 1; top->eval();\n"
           << "        trace->dump(now); now += 5;\n"
           << "        top->" << *clock << " = 0; top->eval();\n"
           << "        trace->dump(now); now += 5;\n";
    } else {
        os << "        top->eval();\n"
           << "        trace->dump(now); now += 10;\n";
    }

    os << "    }\n\n"
       << "    trace->close();\n"
       << "    top->final();\n"
       << "    delete top;\n"
       << "    delete trace;\n"
       << "    return 0;\n"
       << "}\n";

    return os.str();
}

}  // namespace simgen
}  // namespace smart
