// BlockRunner: run synthesis blocks in parallel, each with its own deadline.
//
// A block runs as a CHILD PROCESS, not a thread. That is a deliberate choice,
// not inertia: the VCD scanner is generated by flex without `%option
// reentrant` and keeps file-scope state (`static VCDParser::location loc;`),
// so two blocks parsing traces in one process would corrupt each other. The
// block code also reaches for globals throughout (smart.cpp) and shells out to
// cvc5 and EBMC. A process per block keeps all of that isolated and makes the
// per-block timeout enforceable — a thread stuck inside cvc5 cannot be
// cancelled, a process can.
//
// This replaces the old `timeout 100 ./smart.out ...` subprocess trick: the
// deadline is enforced here, by us, and a timed-out block's whole process
// group is killed rather than just its leader.

#ifndef SMART_PIPELINE_BLOCKRUNNER_H
#define SMART_PIPELINE_BLOCKRUNNER_H

#include <chrono>
#include <functional>
#include <string>
#include <vector>

namespace smart {
namespace pipeline {

struct BlockJob {
    std::string variablesFile;  // this block's variable subset
    std::string resultFile;     // where the block writes its assertion
    std::string coreId;         // identifies the block in logs and scratch dirs
    int latency = 0;            // LTL latency; 0 = plain safety
};

enum class BlockStatus { Verified, NoAssertion, TimedOut, Failed };

struct BlockResult {
    BlockJob job;
    BlockStatus status = BlockStatus::Failed;
    int exitCode = 0;
    double seconds = 0.0;
    std::string assertion;  // set when status == Verified
    int pid = 0;            // for correlating with the block's own log
    bool killed = false;    // deadline expired and we killed the group
    bool survivedKill = false;  // ... and something was still alive after
};

struct BlockRunnerOptions {
    std::string executable;   // the binary to exec (this one, by default)
    std::string workDir;      // child's working directory
    std::string topModule;
    std::string configPath;   // resolved config, in the new flat schema
    std::string logsDir;
    int jobs = 1;
    int coreTimeoutSeconds = 100;
};

// Run every job, at most `jobs` at a time, respecting `deadline` for the whole
// round. Jobs not started before the deadline are reported as TimedOut without
// being run. `progress` is called (from one thread at a time) after each job.
std::vector<BlockResult> runBlocks(
    const std::vector<BlockJob>& jobs, const BlockRunnerOptions& options,
    std::chrono::steady_clock::time_point deadline,
    const std::function<void(const BlockResult&, std::size_t done,
                             std::size_t total)>& progress);

// Entry point for a single block, i.e. what the child process runs. Defined in
// smart.cpp; it is the old `main()` there, unchanged apart from its name.
// NOT reentrant — smart.cpp keeps its state in globals. One call per process.
int runSmartBlock(int argc, char** argv);

}  // namespace pipeline
}  // namespace smart

#endif  // SMART_PIPELINE_BLOCKRUNNER_H
